# .System Configuration
version: '{build}'
image:
    #- Ubuntu
    - Visual Studio 2019

# Set the specific version of Node.js
environment:
  nodejs_version: "10"
  APPVEYOR_YML_DISABLE_PS_LINUX: true
 
# Install scripts. (runs after repo cloning)
install:
  # Install Node.js
  - sh: nvm install $nodejs_version
  - ps: Install-Product node $env:nodejs_version
  
  # Output useful info for debugging.
  - echo "ENVIRONMENT SETUP INFO"
  - node --version
  - npm --version
  - dotnet --version
  
  # install modules
  - npm install
  
# Nuget restore before build    
before_build:
    - dotnet restore

# Build
build:
    project: Kentico.Components.sln
    verbosity: minimal

configuration:
    - Release

# .NET Tests
test:
  assemblies:
    only:
    - '**\kentico.*.Tests.dll'

# Post-install test scripts.
after_test:
  # Run build & tests
  - npm run build
  - npm run test